// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-1j_Q42O_DXjOwdcwXzz5rcyslxi6QbI',
    appId: '1:934589307904:web:9eb88704ad267c90b94ce5',
    messagingSenderId: '934589307904',
    projectId: 'date-sketch',
    authDomain: 'date-sketch.firebaseapp.com',
    storageBucket: 'date-sketch.firebasestorage.app',
    measurementId: 'G-PB1T66R48D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsxuGH_oU_4JAnDpdD09fjxXbymPlSRAs',
    appId: '1:934589307904:android:efa79fa2eb6e7eacb94ce5',
    messagingSenderId: '934589307904',
    projectId: 'date-sketch',
    storageBucket: 'date-sketch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCna3eDXd_jj05oyed7EjNp-dhnhcKjN48',
    appId: '1:934589307904:ios:33e6b55fce24e079b94ce5',
    messagingSenderId: '934589307904',
    projectId: 'date-sketch',
    storageBucket: 'date-sketch.firebasestorage.app',
    androidClientId: '934589307904-4ul12nd78d37fsuv709grj8r29g3oncr.apps.googleusercontent.com',
    iosClientId: '934589307904-9gbs3k2gu9hqovj8n280k3mkspbtvctf.apps.googleusercontent.com',
    iosBundleId: 'com.buelmanager.datesketchwithai.dateSketchWithAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCna3eDXd_jj05oyed7EjNp-dhnhcKjN48',
    appId: '1:934589307904:ios:33e6b55fce24e079b94ce5',
    messagingSenderId: '934589307904',
    projectId: 'date-sketch',
    storageBucket: 'date-sketch.firebasestorage.app',
    androidClientId: '934589307904-4ul12nd78d37fsuv709grj8r29g3oncr.apps.googleusercontent.com',
    iosClientId: '934589307904-9gbs3k2gu9hqovj8n280k3mkspbtvctf.apps.googleusercontent.com',
    iosBundleId: 'com.buelmanager.datesketchwithai.dateSketchWithAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-1j_Q42O_DXjOwdcwXzz5rcyslxi6QbI',
    appId: '1:934589307904:web:9eb88704ad267c90b94ce5',
    messagingSenderId: '934589307904',
    projectId: 'date-sketch',
    authDomain: 'date-sketch.firebaseapp.com',
    storageBucket: 'date-sketch.firebasestorage.app',
    measurementId: 'G-PB1T66R48D',
  );

}